# github
[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

#[[plugins]]
#repo = 'Shougo/vimproc.vim', {
#\ 'build' : {
#\     'windows' : 'tools\\update-dll-mingw',
#\     'cygwin' : 'make -f make_cygwin.mak',
#\     'mac' : 'make -f make_mac.mak',
#\     'linux' : 'make',
#\     'unix' : 'gmake',
#\    },
#\ }

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tpope/vim-fugitive'

#[[plugins]]
# repo = 'kien/ctrlp.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

#[[plugins]]
#repo = 'thinca/vim-quickrun', {
#      \ 'depends' : 'mattn/quickrunex-vim',
#      \ }

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-scripts/Align'

#[[plugins]]
#repo = 'majutsushi/tagbar', {
#      \ 'build': {
#      \   'mac': 'brew install ctags',
#      \ }
#      \ }

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'rhysd/unite-n3337'

#[[plugins]]
# repo = 'rhysd/wandbox-vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'osyo-manga/vim-over'

# www.vim.org
#[[plugins]]
#repo = 'ShowMarks7'

[[plugins]]
repo = 'vim-scripts/project.tar.gz'

